// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB_o1R55odpt7ebjTZBw0-WBjtqn_LLEE',
    appId: '1:368708347363:web:3543ed1b4788643f64acd6',
    messagingSenderId: '368708347363',
    projectId: 'ujikel',
    authDomain: 'ujikel.firebaseapp.com',
    storageBucket: 'ujikel.firebasestorage.app',
    measurementId: 'G-WKJT8HGTSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSaw6PyxnEZc5FKDooBlY_JZ5KdsdM2o',
    appId: '1:368708347363:android:525667bdf028d54464acd6',
    messagingSenderId: '368708347363',
    projectId: 'ujikel',
    storageBucket: 'ujikel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdsLI7p7VLwqPT0ufVCfnPFTYbjjK61qA',
    appId: '1:368708347363:ios:6c79f37d57d31bbb64acd6',
    messagingSenderId: '368708347363',
    projectId: 'ujikel',
    storageBucket: 'ujikel.firebasestorage.app',
    iosBundleId: 'com.example.ujikel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdsLI7p7VLwqPT0ufVCfnPFTYbjjK61qA',
    appId: '1:368708347363:ios:6c79f37d57d31bbb64acd6',
    messagingSenderId: '368708347363',
    projectId: 'ujikel',
    storageBucket: 'ujikel.firebasestorage.app',
    iosBundleId: 'com.example.ujikel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB_o1R55odpt7ebjTZBw0-WBjtqn_LLEE',
    appId: '1:368708347363:web:e0d9488368ce03db64acd6',
    messagingSenderId: '368708347363',
    projectId: 'ujikel',
    authDomain: 'ujikel.firebaseapp.com',
    storageBucket: 'ujikel.firebasestorage.app',
    measurementId: 'G-ELNEH0NZJZ',
  );
}